# Docker Compose for Development
version: '3.8'

services:
  todo-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    container_name: todo-list-dev
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - todo-dev-network

networks:
  todo-dev-network:
    driver: bridge
